### ISSUE TITLE
Eccezzione  io.jsonwebtoken.UnsupportedJwtException: Signed Claims JWSs are not supported.

### ISSUE THREAD

**Issue by MarcoKnezevichInsiel** [ministero-salute/it-fse-gtw-tools#2]
Ciao, credo di aver trovato un errore nel progetto per la generazione dei token, nel `Launcher.java`  se il `flagValidation `è _true_ viene invocato il metodo privato `parse `che solleva l'eccezione `io.jsonwebtoken.UnsupportedJwtException: Signed Claims JWSs are not supported`. Si potrebbe sostituire il metodo:

`private static Jwt<Header, Claims> parse(String token, Key privateKey) {
	Jwts.builder().signWith(SignatureAlgorithm.HS256, privateKey).compact();
	return Jwts.parser().setSigningKey(privateKey).parseClaimsJwt(token);
}`

con il metodo:

`private Jws<Claims> parse(String token, Key privateKey) {
	return Jwts.parser().setSigningKey(privateKey).parseClaimsJws(token);
}`

sostituendo `parseClaimsJwt `con `parseClaimsJws `come suggerito [qui](https://stackoverflow.com/questions/61016123/io-jsonwebtoken-unsupportedjwtexception-signed-claims-jwss-are-not-supported).

**Comment by paoluzic** [comment]
Issue #2 fixed by (https://github.com/ministero-salute/it-fse-gtw-tools/commit/3e5ece412733f6e6cce79516afc0972cf6f06ade) in release v0.0.3-SNAPSHOT:
https://github.com/ministero-salute/it-fse-gtw-tools/releases/tag/v0.0.3-SNAPSHOT

Thanks for the tip.
