### ISSUE TITLE
Errore nella generazione dei token (solo su macchine linux)

### ISSUE THREAD

**Issue by MarcoKnezevichInsiel** [ministero-salute/it-fse-gtw-tools#3]
Ciao, credo di aver trovato un errore nel progetto per la generazione dei token, nel `Launcher.java`. Nel metodo `buildToken()` c'è l'istruzione:

```
String cleanedPEM = new String(pem).replace("-----BEGIN PUBLIC KEY-----", "")
				.replaceAll(System.lineSeparator(), "").replace("-----END PUBLIC KEY-----", "")
				.replace("-----BEGIN CERTIFICATE-----", "").replaceAll(System.lineSeparator(), "")
				.replace("-----END CERTIFICATE-----", "").replace("\n", "");
```

Su macchine linux viene generato un token con i caratteri `\r`. Il token viene considerato valido su [jwt.io](https://jwt.io/) ma non passa la validazione del gateway.

Ho visto che aggiungendo anche:

`.replace("\r", "");`

tutto funziona correttamente.

**Comment by pFonziSogei** [comment]
Salve, se il problema è ancora attivo la invito ad apprire una issue su https://github.com/ministero-salute/it-fse-support/issues
